project:
  type: website

website:
  title: "Technical presentations"
  navbar:
    logo: resources/quarto.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



